// tests/testcases.js
// Option 2: Thanglish → Tamil

const cases = [
  // =========================
  // 24 POSITIVE FUNCTIONAL
  // =========================

  {
    id: "Pos_Fun_0001",
    kind: "Pos_Fun",
    name: "Simple daily sentence converts correctly",
    lengthType: "S",
    input: "naan ooruku poren",
    expected: "",
    notes: "Clean daily sentence. Should transliterate correctly to Tamil.",
    coverage: "Daily language usage • Simple sentence • S • Accuracy validation",
  },
  {
    id: "Pos_Fun_0002",
    kind: "Pos_Fun",
    name: "Greeting + question with punctuation",
    lengthType: "S",
    input: "vanakkam! epdi irukinga? ",
    expected: "",
    notes: "Greeting meaning preserved; punctuation kept.",
    coverage: "Greeting / request / response • Interrogative (question) • S • Accuracy validation",
  },
  {
    id: "Pos_Fun_0003",
    kind: "Pos_Fun",
    name: "Polite request sentence",
    lengthType: "M",
    input: "konjam help pannunga, indha form fill panna venum.",
    expected: "",
    notes: "Polite request should convert smoothly.",
    coverage: "Greeting / request / response • Simple sentence • M • Accuracy validation",
  },
  {
    id: "Pos_Fun_0004",
    kind: "Pos_Fun",
    name: "Imperative command",
    lengthType: "S",
    input: "inge vaanga.",
    expected: "",
    notes: "Command form (imperative) should convert correctly.",
    coverage: "Daily language usage • Imperative (command) • S • Accuracy validation",
  },
  {
    id: "Pos_Fun_0005",
    kind: "Pos_Fun",
    name: "Negative short sentence",
    lengthType: "S",
    input: "naan varala.",
    expected: "",
    notes: "Negative form should be preserved.",
    coverage: "Daily language usage • Negation (negative form) • S • Accuracy validation",
  },
  {
    id: "Pos_Fun_0006",
    kind: "Pos_Fun",
    name: "Present tense sentence",
    lengthType: "S",
    input: "naan saappiddu kondu irukiren.",
    expected: "",
    notes: "Present tense should transliterate correctly.",
    coverage: "Daily language usage • Present tense • S • Accuracy validation",
  },
  {
    id: "Pos_Fun_0007",
    kind: "Pos_Fun",
    name: "Past tense sentence",
    lengthType: "S",
    input: "naan netru hospital ponen.",
    expected: "",
    notes: "Past tense form should be correct; English word 'office' may remain.",
    coverage: "Names / places / common English words • Past tense • S • Robustness validation",
  },
  {
    id: "Pos_Fun_0008",
    kind: "Pos_Fun",
    name: "Future tense sentence",
    lengthType: "S",
    input: "naan naalai campus varuven.",
    expected: "",
    notes: "Future tense should convert correctly.",
    coverage: "Daily language usage • Future tense • S • Accuracy validation",
  },
  {
    id: "Pos_Fun_0009",
    kind: "Pos_Fun",
    name: "Interrogative question",
    lengthType: "S",
    input: "neenga enge poringa?",
    expected: "",
    notes: "Question form should keep the question mark.",
    coverage: "Daily language usage • Interrogative (question) • S • Accuracy validation",
  },
  {
    id: "Pos_Fun_0010",
    kind: "Pos_Fun",
    name: "Compound sentence with contrast",
    lengthType: "M",
    input: "naan kadaiku ponan, aana biscuit vaanga maranthuttan.",
    expected: "",
    notes: "Two ideas joined; should maintain punctuation/flow.",
    coverage: "Word combination / phrase pattern • Compound sentence • M • Accuracy validation",
  },
  {
    id: "Pos_Fun_0011",
    kind: "Pos_Fun",
    name: "Complex sentence (condition)",
    lengthType: "M",
    input: "neenga padichaa thaan exam, pass pannuvinga.",
    expected: "",
    notes: "Condition structure should transliterate well.",
    coverage: "Sentence structures • Complex sentence • M • Accuracy validation",
  },
  {
    id: "Pos_Fun_0012",
    kind: "Pos_Fun",
    name: "Pronoun variation (he)",
    lengthType: "S",
    input: "avan computer use pannuraan.",
    expected: "",
    notes: "Pronoun usage should be correct; English word may remain.",
    coverage: "Mixed Singlish/Thanglish + English • Pronoun variation • S • Robustness validation",
  },
  {
    id: "Pos_Fun_0013",
    kind: "Pos_Fun",
    name: "Plural pronoun (we)",
    lengthType: "S",
    input: "naanga kovil poram.",
    expected: "",
    notes: "Plural pronoun should be preserved.",
    coverage: "Daily language usage • Plural form • S • Accuracy validation",
  },
  {
    id: "Pos_Fun_0014",
    kind: "Pos_Fun",
    name: "Joined words (no spaces) - light stress",
    lengthType: "S",
    input: "naanveetukku poren",
    expected: "",
    notes: "System should still produce reasonable Tamil output.",
    coverage: "Word combination / phrase pattern • Simple sentence • S • Robustness validation",
  },
  {
    id: "Pos_Fun_0015",
    kind: "Pos_Fun",
    name: "Repeated words emphasis",
    lengthType: "S",
    input: "seri seri, naalaiku povam.",
    expected: "",
    notes: "Repetition should remain; comma handled.",
    coverage: "Word combination / phrase pattern • Simple sentence • S • Accuracy validation",
  },
  {
    id: "Pos_Fun_0016",
    kind: "Pos_Fun",
    name: "Mixed English brand term (WhatsApp)",
    lengthType: "M",
    input: "naan instagram la message anupinen.",
    expected: "",
    notes: "Brand term should remain readable while rest converts.",
    coverage: "Mixed Thanglish + English • Simple sentence • M • Robustness validation",
  },
  {
    id: "Pos_Fun_0017",
    kind: "Pos_Fun",
    name: "Place name + English common words",
    lengthType: "M",
    input: "naan Jaffna poganum, bus ku late aachu.",
    expected: "",
    notes: "Place name should remain; rest should convert.",
    coverage: "Names / places / common English words • Compound sentence • M • Robustness validation",
  },
  {
    id: "Pos_Fun_0018",
    kind: "Pos_Fun",
    name: "Punctuation stress with symbols",
    lengthType: "S",
    input: "enna machi?! seri...",
    expected: "",
    notes: "Punctuation marks should not break output.",
    coverage: "Punctuation / numbers • Simple sentence • S • Robustness validation",
  },
  {
    id: "Pos_Fun_0019",
    kind: "Pos_Fun",
    name: "Time format embedded",
    lengthType: "M",
    input: "school 8.30 AM ku start aagum.",
    expected: "",
    notes: "Time format should remain; rest converts.",
    coverage: "Punctuation / numbers • Simple sentence • M • Robustness validation",
  },
  {
    id: "Pos_Fun_0020",
    kind: "Pos_Fun",
    name: "Currency + date formats",
    lengthType: "M",
    input: "naan Rs. 5500 kuduthen; date 25/12/2025.",
    expected: "",
    notes: "Currency/date should remain readable; rest converts.",
    coverage: "Punctuation / numbers • Past tense • M • Robustness validation",
  },
  {
    id: "Pos_Fun_0021",
    kind: "Pos_Fun",
    name: "Units of measurement",
    lengthType: "S",
    input: "5 kg paruppu vaanganum.",
    expected: "",
    notes: "Unit 'kg' and number should remain; rest converts.",
    coverage: "Punctuation / numbers • Simple sentence • S • Robustness validation",
  },
  {
    id: "Pos_Fun_0022",
    kind: "Pos_Fun",
    name: "Multiple spaces formatting",
    lengthType: "S",
    input: "naan   naalaiku   varuven",
    expected: "",
    notes: "Extra spaces should not break conversion.",
    coverage: "Formatting (spaces / line breaks / paragraph) • Future tense • S • Robustness validation",
  },
  {
    id: "Pos_Fun_0023",
    kind: "Pos_Fun",
    name: "Line breaks (multi-line input)",
    lengthType: "M",
    input: "naan varen\nnee varriya?",
    expected: "",
    notes: "Line break preserved; output should still convert.",
    coverage: "Formatting (spaces / line breaks / paragraph) • Interrogative (question) • M • Robustness validation",
  },
  {
    id: "Pos_Fun_0024",
    kind: "Pos_Fun",
    name: "Long paragraph input (>= 300 chars)",
    lengthType: "L",
    input:
      "naan innaiku kaalaila early aa ezhundhen. appuram tea kudichitu konjam exercise pannen. " +
      "office poganum nu bus stop ku ponen, aana traffic romba heavy. " +
      "naan time-ku reach aagaa maaten nu bayam irunthuchu. " +
      "aana driver nalla drive pannaaru, so konjam nerathuku office ku vanthuttan.",
    expected: "",
    notes: "Long input robustness; should not freeze or truncate output.",
    coverage: "Formatting (spaces / line breaks / paragraph) • Complex sentence • L • Robustness validation",
  },

  // =========================
  // 10 NEGATIVE FUNCTIONAL
  // =========================

  {
    id: "Neg_Fun_0001",
    kind: "Neg_Fun",
    name: "Ambiguous la/ள/ழ sound mapping causes incorrect meaning",
    lengthType: "S",
    input: "intha palam saapida nalla irukkum",
    expected: "Should NOT produce correct Tamil word for fruit (பழம்)",
    notes: "The word 'palam' is ambiguous and may be converted as 'பலம்' instead of 'பழம்', changing the intended meaning.",
    coverage: "Word combination / phrase pattern • Simple sentence • S • Robustness validation",

  },
  {
    id: "Neg_Fun_0002",
    kind: "Neg_Fun",
    name: "Time format gets distorted (decimal + AM/PM)",
    lengthType: "S",
    input: "naan 7.30 AM ku veeta varen",
    expected: "Time should remain readable as 7.30 AM (should NOT convert 7.30 into Tamil-digit/odd format like 7.௩௦).",
    notes: "Numeric + punctuation robustness. You already saw this bug; mark Fail if time formatting distorts.",
    coverage: "Punctuation / numbers • Simple sentence • S • Robustness validation",
  },
  {
    id: "Neg_Fun_0003",
    kind: "Neg_Fun",
    name: "Excess punctuation not normalized",
    lengthType: "S",
    input: "ennathu???!!!",
    expected: "Output should NOT remain noisy with ???!!!; system should handle excessive punctuation gracefully (normalize / avoid messy output).",
    notes: "If output stays as 'என்ன???!!!' or breaks, mark Fail (robustness limitation).",
    coverage: "Punctuation / numbers • Interrogative (question) • S • Robustness validation",
  },
  {
    id: "Neg_Fun_0004",
    kind: "Neg_Fun",
    name: "Currency + decimal formatting may break",
    lengthType: "S",
    input: "Rs. 7582.50 kuduthuten",
    expected: "Currency and decimal should remain readable as Rs. 7582.50 (should NOT distort dots/convert digits oddly).",
    notes: "Checks numeric formatting preservation under transliteration.",
    coverage: "Punctuation / numbers • Past tense • S • Formatting preservation",
  },
  {
    id: "Neg_Fun_0005",
    kind: "Neg_Fun",
    name: "Date format with slashes may be altered incorrectly",
    lengthType: "S",
    input: "meeting 25/12/2025 la irukku",
    expected: "Date should remain exactly 25/12/2025 (should NOT shuffle digits or insert Tamil digits/punctuation changes).",
    notes: "Slashes + numbers stress test.",
    coverage: "Punctuation / numbers • Simple sentence • S • Formatting preservation",
  },
  {
    id: "Neg_Fun_0006",
    kind: "Neg_Fun",
    name: "Joined words without spaces may fail conversion",
    lengthType: "S",
    input: "ennodananbannaalaikuvaaraan",
    expected: "System should NOT produce unreadable output; ideally it should segment or at least produce a readable Tamil string. If output is garbage/partial, mark Fail.",
    notes: "Joined vs segmented variation stress test (robustness).",
    coverage: "Formatting (spaces / line breaks / paragraph) • Simple sentence • S • Robustness validation"
  },
  {
    id: "Neg_Fun_0007",
    kind: "Neg_Fun",
    name: "Emoji or special characters may cause issues",
    lengthType: "S",
    input: "naan naan varen 😊",
    expected: "",
    notes: "Emoji may be dropped or cause spacing/output glitch.",
    coverage: "Punctuation / numbers • Simple sentence • S • Robustness validation",
  },
  {
    id: "Neg_Fun_0008",
    kind: "Neg_Fun",
    name: "Heavy punctuation + time may behave unexpectedly",
    lengthType: "M",
    input: "seri!!! appo 3:45pm ku ok??",
    expected: "",
    notes: "Punctuation/time formats may cause partial or odd conversion.",
    coverage: "Punctuation / numbers • Interrogative (question) • M • Robustness validation",
  },
  {
   
    id: "Neg_Fun_0009",
    kind: "Neg_Fun",
    name: "Excessively long multi-line input (limit exceed) may truncate or fail",
    lengthType: "L",
    input:
      ("naan innaiku romba busy. work athigama irukku.\n" +
      "meeting onnu irukku. appuram documents submit panna venum.\n" +
      "intha maadhiri niraya task irukkarappo system output slow aaguma nu paakanum.\n" +
      "line breaks oda long input kuduthaa output truncate aagudhaa illa full aa varudhaa nu check pannuren.\n") +
      "<<<END>>>",
    expected: "",
    notes:
      "Negative scenario: input intentionally exceeds typical supported size (very large). " +
      "System may lag, partially convert, truncate output, or show an error/limit message. " +
      "Pass if system handles gracefully (no crash) and indicates truncation/limit OR converts as much as allowed.",
    coverage:
      "Stress/limit testing • Formatting (line breaks) • Large input • Robustness validation",


  },
  {
    id: "Neg_Fun_0010",
    kind: "Neg_Fun",
    name: "Line breaks may produce unstable output",
    lengthType: "M",
    input: "naan varen\nnee enga irukka?\nseri apram pesalam",
    expected: "Line breaks should be preserved and each line should remain readable. If output loses lines / merges incorrectly / inserts junk, mark Fail.",
    notes: "Multi-line input robustness + formatting.",
    coverage: "Formatting (spaces / line breaks / paragraph) • Interrogative (question) • M • Formatting preservation",
  },

  // UI related test cases //
  {
  id: "Pos_UI_0001",
  kind: "Pos_UI",
  name: "UI updates Tamil output in real-time when space is pressed",
  lengthType: "S",
  input: "naanga rendu perum naalaiku kadaiku povam",
  expected: "",
  notes: "Tamil conversion should happen immediately in the same textarea after space key press.",
  coverage: "UI behavior • Real-time update • No button interaction",
  }

];

module.exports = { cases };
